#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

### hd -- HackDepot console client.

# Copyright (C) 2016 Artyom V. Poptsov <poptsov.artyom@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


### Commentary:

# Usage examples:
#
#   Get list of all item IDs:
#   ./hd -u $EMAIL -p $PASSWORD item
#
#   Get information about an item by its ID:
#   ./hd -u $EMAIL -p $PASSWORD item 562dee846d986e7c88000000

### Code:

require 'rest-client'
require 'json'
require 'optparse'
require 'colorize'
require 'yaml'

YAML_CONFIG_FILE = 'hd.yaml'

$options = {}

opt_parser = OptionParser.new do |opt|
  opt.on("-u", "--user=USER", "Set user name.") do |user|
    $options[:user] = user
  end
  opt.on("-p", "--password=PASSWORD", "Set password.") do |password|
    $options[:password] = password
  end

  $options[:nocolor] = false
  opt.on("-n", "--nocolor", "Disable ASCI color codes.") do
    $options[:nocolor] = true
  end

  $options[:insecure] = false
  opt.on("--insecure", "Disable SSL verification.") do
    $options[:insecure] = true
  end
end

opt_parser.parse!


# HackDepot instance domain name.
HACKDEPOT_INSTANCE = 'hd.cadr.nntc.nnov.ru'
API_VERSION = "v1"
API_BASE_URL = "https://#{HACKDEPOT_INSTANCE}/api/#{API_VERSION}"


### Helper methods

# Authenticate with a EMAIL and PASSWORD, return authentication
# response.
def authenticate(email, password)
  request_body_map = {
    :email => email,
    :password => password
  }

  client = RestClient::Resource.new(
    "#{API_BASE_URL}/auth/sign_in",
    :verify_ssl => $options[:insecure] ?
                     OpenSSL::SSL::VERIFY_NONE
                   : OpenSSL::SSL::VERIFY_PEER)

  client.post request_body_map.to_json,
              {:content_type => 'application/json',
               :accept => 'application/json'}
end

# Get IDs of all items registered in HackDepot.  Use ACCESS_TOKEN,
# EXPIRY and CLIENT for authentication.
def get_all_items(user, access_token, expiry, client)
  resource = RestClient::Resource.new(
    "#{API_BASE_URL}/items",
    :verify_ssl => $options[:insecure] ?
                     OpenSSL::SSL::VERIFY_NONE
                   : OpenSSL::SSL::VERIFY_PEER)

  resource.get({
               :content_type => 'application/json',
               :accept => 'application/json',
               :access_token => access_token,
               :token_type => "Bearer",
               :expiry => expiry,
               :client => client,
               :uid => user
             })
end

# Get information about item with ID.  Use ACCESS_TOKEN, EXPIRY and
# CLIENT for authentication.
def get_item(user, id, access_token, expiry, client)
  resource = RestClient::Resource.new(
    "#{API_BASE_URL}/items/#{id}",
    :verify_ssl => $options[:insecure] ?
                     OpenSSL::SSL::VERIFY_NONE
                   : OpenSSL::SSL::VERIFY_PEER)
  resource.get({
               :content_type => 'application/json',
               :accept => 'application/json',
               :access_token => access_token,
               :token_type => "Bearer",
               :expiry => expiry,
               :client => client,
               :uid => user
             })
end

# Print IDs of items from an ARRAY to stdout.
def print_item_list(array)
  max_title_len = array.inject(20) do |p, e|
    e['title'].length > p ? e['title'].length : p
  end

  array.each { |elem|
    sn = elem['serial']
    printf "%s: %-#{max_title_len}s %s\n",
           elem['id']['$oid'],
           elem['title'],
           if not sn == nil and not sn.empty?
             " (S/N: #{sn})"
           else
             ""
           end
  }
end

# Print an ITEM to stdout in a human-friendly manner.
def print_item(item)
  if $options[:nocolor] == true
    p = proc { |key, value|
          printf "%s: %s", key, value
    }
  else
    p = proc { |key, value|
          print "#{key}: ".green
          puts value
    }
  end

  item.each_pair(&p)
end


###

# Handle "item" command.
def handle_item(config, args)
  if config
    user = config['HackDepot']['user']
    password = config['HackDepot']['password']
  end

  user = $options[:user] ? $options[:user] : user
  password = $options[:password] ? $options[:password] : password

  user or raise "'user' should be specified."
  password or raise "'password' should be specified"

  auth_rsp = authenticate user, password

  if not args[1] == nil
    rsp = get_item user,
                   args[1],
                   auth_rsp.headers[:access_token],
                   auth_rsp.headers[:expiry],
                   auth_rsp.headers[:client]
    print_item JSON.parse(rsp)
  else
    rsp = get_all_items user,
                        auth_rsp.headers[:access_token],
                        auth_rsp.headers[:expiry],
                        auth_rsp.headers[:client]

    print_item_list JSON.parse(rsp.body)
  end
end

def print_help_and_exit
  puts "\
Usage: hd command [args]

Options:
  -u, --user=USER        User name for authenticaton.
  -p, --password=PASSWORD
                         Password for authentication.
  --insecure             Disable SSL verification.

Commands:
  item        Query HackDepot instance for items.
  help        Print this message and exit.
"
  exit
end


### Entry point

def main
  begin
    config = YAML.load_file(YAML_CONFIG_FILE)
  rescue
    config = nil
  end

  case ARGV[0]
  when "item"
    handle_item config, ARGV
  else
    print_help_and_exit
  end
end

main

### hd ends here.
